app:
  name: "web_app"
  mode: "dev"
  port: 8095
  version: "v0.1.5"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "web_app"
  username: "root"
  password: "20212021"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: "20212021"
  pool_size: 20
  min_idle_conns: 5